/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBuilderRouteImport } from './routes/_app.builder'
import { Route as AppAgreementsRouteImport } from './routes/_app.agreements'
import { Route as AppAgreementsIdRouteImport } from './routes/_app.agreements.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBuilderRoute = AppBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementsRoute = AppAgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementsIdRoute = AppAgreementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAgreementsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agreements': typeof AppAgreementsRouteWithChildren
  '/builder': typeof AppBuilderRoute
  '/dashboard': typeof AppDashboardRoute
  '/agreements/$id': typeof AppAgreementsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agreements': typeof AppAgreementsRouteWithChildren
  '/builder': typeof AppBuilderRoute
  '/dashboard': typeof AppDashboardRoute
  '/agreements/$id': typeof AppAgreementsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/agreements': typeof AppAgreementsRouteWithChildren
  '/_app/builder': typeof AppBuilderRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/agreements/$id': typeof AppAgreementsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agreements' | '/builder' | '/dashboard' | '/agreements/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agreements' | '/builder' | '/dashboard' | '/agreements/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/agreements'
    | '/_app/builder'
    | '/_app/dashboard'
    | '/_app/agreements/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builder': {
      id: '/_app/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AppBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agreements': {
      id: '/_app/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AppAgreementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agreements/$id': {
      id: '/_app/agreements/$id'
      path: '/$id'
      fullPath: '/agreements/$id'
      preLoaderRoute: typeof AppAgreementsIdRouteImport
      parentRoute: typeof AppAgreementsRoute
    }
  }
}

interface AppAgreementsRouteChildren {
  AppAgreementsIdRoute: typeof AppAgreementsIdRoute
}

const AppAgreementsRouteChildren: AppAgreementsRouteChildren = {
  AppAgreementsIdRoute: AppAgreementsIdRoute,
}

const AppAgreementsRouteWithChildren = AppAgreementsRoute._addFileChildren(
  AppAgreementsRouteChildren,
)

interface AppRouteChildren {
  AppAgreementsRoute: typeof AppAgreementsRouteWithChildren
  AppBuilderRoute: typeof AppBuilderRoute
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgreementsRoute: AppAgreementsRouteWithChildren,
  AppBuilderRoute: AppBuilderRoute,
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
